- package-lock.json
- package.json
- src/components/incident/detailed_view_modal.js
- src/components/incident/incident_home.js
- src/components/incident/incident_table.js
- src/components/incident/new_incident_drawer.js
- src/components/incident/update_incident_drawer.js
> Markdown support. Bugs for text box sizes.

- src/api_calls/build_calls.js
- src/api_calls/build_health_calls.js
- src/api_calls/incident_calls.js
- src/api_calls/release_calls.js
React needs to have the word `REACT_APP_` in front of environment variables for it to be exposed at `process.env.REACT_APP_<env variable>`
https://create-react-app.dev/docs/adding-custom-environment-variables/
> Update route env variable

- src/components/build/datepicker_filter.js
- src/components/build/run_status_filter.js
Update table names to the correct ones.
> Table name fixes

- README.md
- components/api_calls/release_calls.js
- components/release/openshift_version_select.js
Use the migrated API endpoint from the back-end server.
> Use API endpoint

- .env
- Dockerfile.update
- components/api_calls/build_calls.js
- components/build/build_history_table.js
- components/build/run_status_filter.js
- pages/dashboard/build/history/index.js
- pages/dashboard/release/[releaseVersion].js
> Add build page

- .env
- .env.development
- .env.production
- components/api_calls/build_calls.js
Created dev and production .env files and removed values in .env that are not used. Created a table column to provide task details.
> Clean env files, add task link

- components/build/build_history_table.js
- pages/dashboard/build/history/index.js
- pages/dashboard/release/[releaseVersion].js
Commit was dropped in the previous PR due to some issue. Adding Task ID link along with lint changes.
> Add task link

- components/api_calls/build_calls.js
- components/build/build_history_table.js
- pages/dashboard/build/history/index.js
Make the build page fields searchable
> Make fields searchable

- components/api_calls/build_calls.js
- pages/dashboard/build/history/index.js
Enable partial search for build page fields.
> Enable partial search

- components/api_calls/build_calls.js
- components/build/build_history_table.js
- pages/dashboard/build/history/index.js
Enable partial search with quotes and add info icon with popover.
> Enable exact search, add info icon

- components/release/release_branch_detail_table.js
Display advisory type (eg: RHSA) on the release status page.
> [ART-5870] Show advisory type

- components/release/release_branch_detail_table.js
Show advisory type on art-dashboard release status page.
> Show advisory type

- components/release/release_branch_detail.js
Display Release ticket link below the release name.
> [ART-5871] show jira link

- .github/workflows/snyk_security.yaml
Steps
- Get the github token by following this [doc](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) using openshift-art-build-bot credentials on bitwarden. Generate a JWT token first and using that generate a github token
- Add a secret to the repo by using GitHub API endpoint ([docs](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret)) _(but make sure to check if a secret with the same name doesn't exist, else the new value will overwrite the old one!)_
- You will need the repository public key, which you can get from [here](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#get-a-repository-public-key)
- And also the encrypt the …
> Setup snyk (https://issues.redhat.com/browse/ART-6354)

- components/release/release_branch_detail.js
Getting a null value since data hasn't been received from backend. Adding to if block.
> Handle null for API data

- .env.production
Point art-dash ui to the server on the new cluster
> Switch to new cluster

- components/release/RpmsImagesList.js
- pages/dashboard/rpm_images/index.js
This commit includes several updates to the frontend that make the website more consistent and user-friendly. These changes include:
- Introduced a loading message to provide users feedback during data fetches. The loading message now accurately reflects the state of the page load and only disappears when the RPMs and Images are fully loaded.
- Added a state hook to control the display of the loading message and pass it down to the 'RpmsImagesList' component to signal when the data fetching is complete.
- Updated the 'RpmImages' component to match the styling and layout of the 'ReleaseHomePage' component. This includes changes to the version header and layout structure.
- Added a new title in the 'RpmsImagesList' component, "RPMs and Images the ART Team is Currently Building", providing …
> Polish frontend for better consistency and user experience

- components/api_calls/api_calls.js
- components/login/Login.js
- components/login/LoginButton.js
- pages/index.js
- pages/private/privatePage.js
- styles/Login.module.css
Added Login.js component, withAuth.js component, and related pages and styles. Also updated api_calls.js and index.js files to correlate these changes
> Implement login functionality and private page

- components/api_calls/api_calls.js
- pages/private/privatePage.js
This reverts commit 47b6b50c4a3ac33e7fce0b20ece007001ffc3797.
> Revert "added missing import, small changes/nitpicks"

- components/api_calls/api_calls.js
- components/login/Login.js
- Introduced a  function to fetch cookies from the browser, improving the API call mechanism.
- Adjusted the  method in the API calls module to use the newly introduced  function for token-based authentication.
- Enhanced the Login component to store the authentication token in a cookie upon a successful login.
- Refactored the Login component to adapt to the new token-based authentication approach.
> Enhanced Authentication and API Call Mechanisms

- components/api_calls/api_calls.js
- components/login/Login.js
Reverts openshift-eng/art-dashboard-ui#74
> Revert "Enhanced Authentication and API Call Mechanisms"

- components/release/release_branch_detail.js
- pages/private/privatePage.js
-  introduce pagination and remove 'previous' advisory handling, this way there will be all releases that follow the hardcoded requirments like brew_link, jira_link...
- also remove debugging command console.log
> [ART-7621] Update frontend to align with backend changes

- pages/dashboard/build/history/index.js
Enhanced the BUILD_HISTORY_HOME component to support URL filtering. This update enables the users to filter the build status page based on various parameters directly through the URL. For instance, navigating to art-dash.engineering.redhat.com/dashboard/build/history?group=openshift-4.11 (you can try this by going to my hackspace url: https://art-dash-hackspace-martin.apps.artc2023.pc3z.p1.openshiftapps.com/dashboard/build/history?group=openshift-4.11, it will automatically apply the respective filters on the page.
The changes also ensure that any filters applied on the page are reflected in the URL, which provides a more interactive and user-friendly experience.
This was achieved by:
- Importing and utilizing the useRouter hook from next/router to listen for route changes.
- Creating a …
> [ART-5986] Allow URL filtering for build status page

- components/api_calls/build_calls.js
Enhanced the clarity and functionality of the getBuilds function:
- Introduced a clear check for whether a value is enclosed in quotes.
- Grouped logic for exact and partial matches based on keys, improving readability.
- Added comments for better code understanding.
> [ART-8100] Refactor searchParams processing in getBuilds

- components/release/openshift_version_select.js
- components/release/release_branch_detail.js
- pages/dashboard/release/[releaseVersion].js
This commit introduces several improvements:
- Updated the OpenshiftVersionSelect component to prevent unnecessary redirects when the selected version is the same as the initial version.
- Reworked ReleaseBranchDetail to use React's useCallback and useEffect for more efficient data fetching and state management.
- Added loading messages to improve user experience during data fetch operations.
- Implemented a new pagination system in ReleaseBranchDetail for better navigation.
- Refactored [releaseVersion].js page to handle release version changes more efficiently. These changes aim to enhance the usability and performance of the dashboard.
tldr; pagination reflected in url, loading works properly,
> [ART-8798] Enhanced Navigation and Loading in art-dashboard-ui

- components/self-service/new-content-checklist.tsx
- components/self-service/new-content-form.tsx
Ref https://issues.redhat.com/browse/ART-9554
UI changes.
> [ART-9554] Update page

- package-lock.json
- package.json
Reverts openshift-eng/art-dashboard-ui#111
> Revert "Bump next from 13.5.6 to 14.1.1"

- Dockerfile
> Bump node to 20

- components/self-service/new-content-done.tsx
Reverts openshift-eng/art-dashboard-ui#143
> Revert "ART-12168: fixed variables coming from onboarding form"

- app.py
Ref [ART-11593](https://issues.redhat.com/browse/ART-11593)
> ART-11593 Improve get_versions() to fetch available OCP versions from build-data

- static/script.js
- static/style.css
Ref. [ART-11435](https://issues.redhat.com/browse/ART-11435)
> ART-11435 UI improvements

- static/script.js
- templates/index.html
Ref. [ART-11624](https://issues.redhat.com/browse/ART-11624)
> ART-11624 Use a Flatpick date picker

- app.py
- static/script.js
- templates/index.html
Ref. [ART-11639](https://issues.redhat.com/browse/ART-11639)
> ART-11639 Fix results caching when opening a query URL

- app.py
- static/style.css
- templates/index.html
[ART-12897](https://issues.redhat.com/browse/ART-12897)
> ART-12897 Also search for bundles

- components/self-service/new-content-checklist.tsx
ref: https://redhat-internal.slack.com/archives/CB95J6R4N/p1757516142921869?thread_ts=1757492151.999009&cid=CB95J6R4N
> Update threat assessment link
